### ISSUE TITLE
1.20.6 Support!

### ISSUE THREAD

**Issue by Soufre** [Dev0Louis/Mendingless-Netherite#1]
This mod brings a cool new vanilla-friendly challenge that I'd love to have in the latest version of Minecraft, I would be really happy if you updated this mod after a year of inactivity.

**Comment by Dev0Louis** [comment]
I updated the mod to 1.20.6. You can get the mod on modrinth.
https://modrinth.com/mod/mendingless-netherite/version/1.1+1.20.6
